services:
  app:
    build:
      context: .
      args:
        JAR: ./target/dummy-sales-log-*.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      LOGGING_LEVEL_COM_YO1000_SALESLOG_AOP: debug
      APP_MONITOR_ENABLED: true
      APP_THREAD_NOISESPERSEC: 200
      #APP_DATA_TYPE: file
      #APP_DATA_FILE_PATH: /var/tmp/sales-log/data.json
      APP_DATA_TYPE: db
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/saleslog
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DEFERDATASOURCEINITIALIZATION: true
      SPRING_JPA_HIBERNATE_DDLAUTO: create
      SPRING_JPA_SHOWSQL: false
    volumes:
      - ./target/sales-log:/var/tmp/sales-log
    ports:
      - 8080:8080

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: saleslog
      POSTGRES_PASSWORD: postgres
    command: |
      postgres -c 'max_connections=2000'

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafka-ui:
    image: provectuslabs/kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - 8888:8080
    depends_on:
      - kafka
