spring:
  application.name: dummy-sales-log
  kafka:
    bootstrap-servers:

    template:
      default-topic: sales-log

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json:
          add.type.headers: false
  datasource:
    url:
    username:
    password:

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    com.yo1000.saleslog: info

app:
  time-compression:
    initial-date: 1999-02-11
  data:
    type: mem
  thread:
    noises-per-sec: 0
