name: Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build
        run: |
          mvn clean test

  package:
    if: contains(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build
        run: |
          mvn -DskipTests clean package
      - uses: actions/upload-artifact@v2
        with:
          name: package-${{ matrix.os }}
          path: target

  container:
    if: contains(github.ref, 'refs/tags/')
    needs: [test, package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: package-ubuntu-latest
          path: target
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          ls -al target
          
          VERSION=$(echo '${{ github.ref }}' | sed -e 's/refs\/tags\///g' | sed -e 's/refs\/heads\///g')
          
          docker build -t yo1000/dummy-sales-log:$VERSION --build-arg JAR=target/dummy-sales-log-*.jar .
          docker image ls
          
          docker tag yo1000/dummy-sales-log:$VERSION ghcr.io/yo1000/dummy-sales-log:$VERSION
          docker tag yo1000/dummy-sales-log:$VERSION ghcr.io/yo1000/dummy-sales-log:latest
          
          docker push ghcr.io/yo1000/dummy-sales-log:$VERSION
          docker push ghcr.io/yo1000/dummy-sales-log:latest
